# Generated by Django 2.1 on 2018-11-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrieNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.CharField(max_length=50)),
                ('is_full_username', models.BooleanField(default=False)),
                ('json_dict', models.CharField(max_length=150)),
            ],
        ),
    ]
