# Generated by Django 2.1 on 2018-11-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trienode',
            name='json_dict',
        ),
        migrations.AddField(
            model_name='trienode',
            name='usernames',
            field=models.CharField(default='', max_length=3000),
            preserve_default=False,
        ),
    ]
