# Generated by Django 2.1 on 2018-11-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0002_auto_20181113_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trienode',
            name='is_full_username',
        ),
    ]
