# Generated by Django 2.1 on 2019-02-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0003_remove_trienode_is_full_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrieNode',
            new_name='SearchNode',
        ),
    ]
