# Generated by Django 2.1 on 2018-12-04 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Posts', '0009_auto_20181130_1627'),
        ('Users', '0007_remove_profile_profile_pic_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, to='Users.Profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Posts.Post')),
            ],
        ),
    ]
