# Generated by Django 2.1 on 2018-11-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='owner_string',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
