# Generated by Django 2.1 on 2018-11-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_post_owner_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
