# Generated by Django 2.1 on 2018-11-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_post_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
    ]
