# Generated by Django 2.1 on 2018-11-30 16:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_auto_20181129_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 16, 26, 56, 41860, tzinfo=utc)),
        ),
    ]
