# Generated by Django 2.1 on 2019-01-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0009_auto_20181130_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_id',
        ),
    ]
