# Generated by Django 2.1 on 2018-11-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers_string',
            field=models.CharField(default='', max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='follows_string',
            field=models.CharField(default='', max_length=3000),
            preserve_default=False,
        ),
    ]
