# Generated by Django 2.1 on 2018-11-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20181111_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='follows_count',
            field=models.IntegerField(default=0),
        ),
    ]
